version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
  vector-db:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # API port
      - "6334:6334"  # Optional, for gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage  # Persist data on the host machine
    environment:
      QDRANT__STORAGE__PATH: "/qdrant/storage"
      QDRANT__LOG__LEVEL: "info"